### ISSUE TITLE
Missing Config.json template

### ISSUE THREAD

**Issue by C4Wiz** [mammo0/Repository-Bootstrapper#1]
not sure how to setup the config.json file without a template

**Comment by mammo0** [comment]
Hello,

the `config.json` gets created by the script based on the CLI arguments. A creation by the user is not intended.

On the first run of the script you need to supply all arguments via CLI. You'll get an error message about missing or wrong arguments.
After a successful run you see the `config.json` file in the directory of the script. Afterwards you only call the script without any arguments. The required settings are then read from the `config.json` file.
If you want to update a setting, just call the script with the corresponding CLI argument and the setting in the `config.json` file will get changed.

Maybe I'll find some time to write a better README.md

**Comment by C4Wiz** [comment]
So what is the cli argument syntax?

On Aug 30, 2022, at 9:31 AM, mammo0 ***@***.***> wrote:

﻿

Hello,

the config.json gets created by the script based on the CLI arguments. A creation by the user is not intended.

On the first run of the script you need to supply all arguments via CLI. You'll get an error message about missing or wrong arguments.
After a successful run you see the config.json file in the directory of the script. Afterwards you only call the script without any arguments. The required settings are then read from the config.json file.
If you want to update a setting, just call the script with the corresponding CLI argument and the setting in the config.json file will get changed.

Maybe I'll find some time to write a better README.md

**Comment by mammo0** [comment]
Please use the `-h` resp. `--help` argument

```shell
python generate_repo.py -h
```

**Comment by C4Wiz** [comment]
i was really hoping to take advantage of the python 3 rewrite, and some of the features you added, but your version is way over complicated! no documentation makes it a non starter for me, i'll stick with Twilight0's version

**Comment by mammo0** [comment]
What CLI arguments you don't understand?

Are you getting an error? If so, please provide the error message.

As I mentioned above, I know that there's no documentation. I did just a quick rewrite for me to fit my needs.
However I can try to create a documentation the next days... But I have to find some free time for this.

**Comment by C4Wiz** [comment]
here is my current config from twilights version:

```
[addon]
name=C4Wiz Repo
id=repository.c4wiz
version=1.0.0
author=C4Wiz
summary=C4Wiz Personal Repo
description=Home of the Estuary.ModV2-Modified Skin

[locations]
url=https://raw.githubusercontent.com/C4Wiz/
output_path=Kodi_Repo/
branch=master/
```

**Comment by C4Wiz** [comment]
i got it figured out!

**Comment by mammo0** [comment]
> i got it figured out!

Ok, I'm glad it works for you now. What was your main problem? And how you solved it?

Maybe I can improve this?

**Comment by C4Wiz** [comment]
> > i got it figured out!
> 
> Ok, I'm glad it works for you now. What was your main problem? And how you solved it?
> 
> Maybe I can improve this?

just alot of typing for initial setup and escaping spaces in folder names.

i see 2 issues so far:

1: missing a / in the template for <datadir zip="true">{url}</datadir> should be <datadir zip="true">{url}/</datadir>
2: script does not look in resources folder of addons for icon.jpg and fanart.jpg (common in skins)

**Comment by mammo0** [comment]
Thanks for these hints.
I will look at them if I have some free time.

**Comment by mammo0** [comment]
I've made some changes to the script. Please look at the latest commits.

> 2: script does not look in resources folder of addons for icon.jpg and fanart.jpg (common in skins)

I've addressed this issue and it should work now. (30b7840)

I've also added an example for the config.json file. (887df83)

**But I've made a breaking change (7d7188b):** You need to update your config.json file before the next run of the script, because I changed the naming of the settings.

**Comment by C4Wiz** [comment]
ok, so the icon.png and fanart.jpg are now copied from the resources folder but the resources folder is not created. the path needs to be identical to the addon.xml

<img width="193" alt="Screen Shot 2022-08-31 at 8 38 41 AM" src="https://user-images.githubusercontent.com/3883521/187680265-31c03911-88e4-4b04-bb94-c29db89ced97.png">

**Comment by mammo0** [comment]
Why should the resources folder be created?

The directory structure of a repository is described in the Kodi wiki: https://kodi.wiki/view/Add-on_repositories (chapter 2)

**Comment by C4Wiz** [comment]
> Why should the resources folder be created?
> 
> The directory structure of a repository is described in the Kodi wiki: https://kodi.wiki/view/Add-on_repositories (chapter 2)

In addition, each add-on directory should contain icon.png, fanart.jpg, changelog-x.y.z.txt and all files from the [Addon.xml#.3Cassets.3E](https://kodi.wiki/view/Addon.xml#.3Cassets.3E) element.

```
<assets>
    <icon>resources/icon.png</icon>
    <fanart>resources/fanart.jpg</fanart>
    <banner>resources/banner.jpg</banner>
    <clearlogo>resources/clearlogo.png</clearlogo>
    <screenshot>resources/screenshot-01.jpg</screenshot>
    <screenshot>resources/screenshot-02.jpg</screenshot>
    <screenshot>resources/screenshot-03.jpg</screenshot>
    <screenshot>resources/screenshot-04.jpg</screenshot>
  </assets>
```

**Comment by mammo0** [comment]
> In addition, each add-on directory should contain icon.png, fanart.jpg, changelog-x.y.z.txt and all files from the [Addon.xml#.3Cassets.3E](https://kodi.wiki/view/Addon.xml#.3Cassets.3E) element.

I understand it like that all resource files from the "assets" tag should be in the root of the addon directory, not in a sub-directory

**Comment by C4Wiz** [comment]
here is a screenshot from another skin repo:
<img width="417" alt="Screen Shot 2022-08-31 at 9 39 57 AM" src="https://user-images.githubusercontent.com/3883521/187692461-47fe1f05-72b1-4285-90f4-e1617fdb4c7b.png">

**Comment by mammo0** [comment]
Hm... Does e.g. the addon icon show up in Kodi if you use your repository?

If not, I will change it.

**Comment by mammo0** [comment]
@C4Wiz please have a look at PR #3 

Does it make a difference in Kodi?

**Comment by C4Wiz** [comment]
> Hm... Does e.g. the addon icon show up in Kodi if you use your repository?
> 
> If not, I will change it.

sorry, took me a bit to track down, your script no longer overwrites the zip files. so my changes were no being sent to my repo.

in testing, the resource folder is not needed for the images to display. sorry for the mis information.

**Comment by mammo0** [comment]
> sorry, took me a bit to track down, your script no longer overwrites the zip files. so my changes were no being sent to my repo.

Yes I changed that behavior. I thought that the addon source would only change if the version also changes.
Should I revert that?

> in testing, the resource folder is not needed for the images to display. sorry for the mis information.

Do you also use resources except `fanart.jpg` and `icon.jpg`. Something like a screenshot? If so, does this also work?
Because `fanart.jpg` and `icon.jpg` are the default assets. So it could be that Kodi tries for compatibility reasons to fetch these two from the root of the addon directory.

**Comment by C4Wiz** [comment]
> > sorry, took me a bit to track down, your script no longer overwrites the zip files. so my changes were no being sent to my repo.
> 
> Yes I changed that behavior. I thought that the addon source would only change if the version also changes. Should I revert that?
> 
> > in testing, the resource folder is not needed for the images to display. sorry for the mis information.
> 
> Do you also use resources except `fanart.jpg` and `icon.jpg`. Something like a screenshot? If so, does this also work? Because `fanart.jpg` and `icon.jpg` are the default assets. So it could be that Kodi tries for compatibility reasons to fetch these two from the root of the addon directory.

**Yes I changed that behavior. I thought that the addon source would only change if the version also changes. Should I revert that?**

perhaps compare md5 sum and overwrite if different

**Do you also use resources except `fanart.jpg` and `icon.jpg`. Something like a screenshot? If so, does this also work? Because `fanart.jpg` and `icon.jpg` are the default assets. So it could be that Kodi tries for compatibility reasons to fetch these two from the root of the addon directory.**

i have not had a chance to test this.

**Comment by mammo0** [comment]
> perhaps compare md5 sum and overwrite if different

I did a simple revert of the corresponding commit. To compare a hash value the new zip file has to be generated anyway.

> i have not had a chance to test this.

No problem. I will keep the above mentioned PR open. Please comment there if this PR should be merged.

I will now close this issue, because the main topic is completed. If you encounter any other problems, feel free to open another one.
